export const ADD_FESELLITY = 'ADD_FESELLITY'
export const DELETE_FESELLITY = 'DELETE_FESELLITY'
export const EDIT_FESELLITY = 'EDIT_FESELLITY'
export const LODAING_FESELLITY = 'LODAING_FESELLITY'
export const GET_FESELLITY = 'GET_FESELLITY'



export const ADD_PRODUCT = 'ADD_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const EDIT_PRODUCT = 'EDIT_PRODUCT'
export const LODAING_PRODUCT = 'LODAING_PRODUCT'
export const GET_PRODUCT = 'GET_PRODUCT'
export const ERROR_PRODUCT = 'ERROR_PRODUCT'


export const GET_SHOP= 'GET_SHOP'

export const GET_SHOPDETAILS= 'GET_SHOPDETAILS'

export const ADD_REVIEW= 'ADD_REVIEW'
export const DELETE_REVIEW = 'DELETE_REVIEW'
export const EDIT_REVIEW = 'EDIT_REVIEW'
export const LODAING_REVIEW = 'LODAING_REVIEW'
export const GET_REVIEW= 'GET_REVIEW'
export const ERROR_REVIEW = 'ERROR_REVIEW'

export const ADD_CART = 'ADD_CART'
export const GET_CART = 'GET_CART'



export const LOADING_CATEGORY = 'LOADING_CATEGORY';
export const GET_CATEGORY = 'GET_CATEGORY';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const ERROR_CATEGORY = 'ERROR_CATEGORY';


export const GET_PRODUCTS = 'GET_PRODUCTS';
export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const EDIT_PRODUCTS = 'EDIT_PRODUCTS';
export const DELETE_PRODUCTS = 'DELETE_PRODUCTS';
export const LOADING_PRODUCTS = 'LOADING_PRODUCTS';
export const ERROR_PRODUCTS = 'ERROR_PRODUCTS';
