export const ADD_FESELLITY = 'ADD_FESELLITY'
export const DELETE_FESELLITY = 'DELETE_FESELLITY'
export const EDIT_FESELLITY = 'EDIT_FESELLITY'
export const LODAING_FESELLITY = 'LODAING_FESELLITY'
export const GET_FESELLITY = 'GET_FESELLITY'



export const ADD_PRODUCT = 'ADD_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const EDIT_PRODUCT = 'EDIT_PRODUCT'
export const LODAING_PRODUCT = 'LODAING_PRODUCT'
export const GET_PRODUCT = 'GET_PRODUCT'
export const ERROR_PRODUCT = 'ERROR_PRODUCT'


export const GET_SHOP= 'GET_SHOP'

export const GET_SHOPDETAILS= 'GET_SHOPDETAILS'
